version = 1

[*]
flash-attn = on
mlock = off
mmap = off
split-mode = none
fit = off
warmup = off
# 2048 is optimal buffer for prefill on ROCm backend. For Vulkan set to 1024 or it will crush
ubatch-size = 2048
batch-size  = 4096
jinja = true
direct-io = on
ctx-checkpoints = 20
swa-full = off

# agentic stuff
cache-prompt = true
cache-reuse = 256
# adjust cache-ram for agents specific conditions
# if full prompt reprocessing is frequent check if cache fits to this value
cache-ram = 4096
slot-prompt-similarity = 0.85

# optimal coding params
top-k = 20
top-p = 0.95
min-p = 0.01
temp = 0.6

# thinking off
reasoning = off
chat-template-kwargs = {"enable_thinking":false}

# spec decoding
spec-type = draft-mtp,ngram-map-k
spec-ngram-map-k-size-n = 6
spec-ngram-map-k-size-m = 4
spec-draft-n-min = 1
spec-draft-n-max = 4
# for preserving quality on specular decoding
spec-draft-p-min = 0.9

[qwen3.6-35B]
model = /home/user/models/Qwen3.6-35B-A3B-GGUF/Qwen3.6-35B-A3B-MTP-UD-Q8_K_XL.gguf
# 524288 for 2 threads = 262144 per each
ctx-size = 524288
#mmproj = /home/user/models/Qwen3.6-35B-A3B-GGUF/mmproj-BF16.gguf

[qwen3.6-27B]
model = /home/user/models/Qwen3.6-27B-GGUF/Qwen3.6-27B-UD-Q8_K_XL.gguf
#mmproj = /home/user/models/Qwen3.6-27B-GGUF/mmproj-BF16.gguf
ctx-size = 524288
load-on-startup = true
