[*]
flash-attn = on
mlock = on
mmap = off
fit-target = 12288
split-mode = none
warmup = on
# This optimal value varies depending on backend, model and MTP. 2048 is max for ROCm, 1024 is max for Vulkan.
ubatch-size = 1024
batch-size  = 4096
jinja = true
metrics = on
direct-io = on
ctx-checkpoints = 8
checkpoint-min-step = 2048
context-shift = on
cache-prompt = true
cache-reuse = 512
cache-ram = 4096
cache-idle-slots = on
slot-prompt-similarity = 0.80
top-k = 20
top-p = 0.95
min-p = 0.01
temp = 0.6
presence-penalty = 0.0
repeat-penalty = 1.05
swa-full = off
no-context-shift = true

# thinking
reasoning = off
reasoning-budget = 0
chat-template-kwargs = {"enable_thinking":false}

# spec decoding
spec-type = draft-mtp,ngram-map-k
spec-draft-n-min = 1
spec-draft-n-max = 4
spec-draft-p-min = 0.4
spec-draft-p-split = 0.6
spec-ngram-map-k-size-n = 6
spec-ngram-map-k-size-m = 4

[qwen3.5-122B]
model = /home/user/models/Qwen3.5-122B-A10B-MTP-GGUF/UD-Q6_K/Qwen3.5-122B-A10B-UD-Q6_K-00001-of-00004.gguf
# I set to lower val for memory saving
cache-ram = 2500

[qwen3.6-27B]
model = /home/user/models/Qwen3.6-27B-GGUF/Qwopus3.6-27B-v2-MTP-Q8_0.gguf
#mmproj = /home/user/models/Qwen3.6-27B-GGUF/mmproj-BF16.gguf
ubatch-size = 512

