version = 1

[*]
flash-attn = on
mlock = off
mmap = off
split-mode = none
fit = off
warmup = off
ubatch-size = 2048
batch-size  = 6144
jinja = true
direct-io = on
ctx-checkpoints = 20
cache-prompt = true
cache-reuse = 256
# adjust cache-ram for agents specific conditions
# if full prompt reprocessing is frequent check if cache fits to this value
cache-ram = 3500
slot-prompt-similarity = 0.85
top-k = 40
top-p = 0.95
min-p = 0.01
swa-full = off
# thinking off
reasoning = off
chat-template-kwargs = {"enable_thinking":false}
draft-p-min = 0.9

[qwen3.6-35B]
model = /home/user/models/Qwen3.6-35B-A3B-GGUF/Qwen3.6-35B-A3B-MTP-UD-Q8_K_XL.gguf
# 524288 for 2 threads = 262144 per each
ctx-size = 524288
#mmproj = /home/user/models/Qwen3.6-35B-A3B-GGUF/mmproj-BF16.gguf
ctx-checkpoints = 30
spec-type = draft-mtp
spec-draft-n-max = 5
temp = 0.6
top-k = 20
#load-on-startup = true

[qwen3.6-27B]
model = /home/user/models/Qwen3.6-27B-GGUF/Qwen3.6-27B-UD-Q8_K_XL.gguf
#mmproj = /home/user/models/Qwen3.6-27B-GGUF/mmproj-BF16.gguf
batch-size = 4096
ctx-checkpoints = 30
spec-type = draft-mtp
spec-draft-n-max = 4
temp = 0.8
load-on-startup = true
